networks:
  expense: {}
  # docker volume create mysql equivalent to below volume creation
volumes:
  mysql:
services:
  backend:
    image: hariniuddagiri/backend:1.0.0
    command: sh -c "sleep 10 && node /opt/backend/index.js" #putting delay of few seconds as backend trying to access mysql before it is up, we put delay to make sure mysql is up before backend is ready to access mysql
    networks:
    - expense
    container_name: backend
    depends_on:
    - mysql

  # docker run -d --name mysql --network expense -v mysql:/var/lib/mysql mysql:1.0.0
  mysql:
    image: hariniuddagiri/mysql:1.0.0
    networks:
    - expense
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql

  frontend:
    image: hariniuddagiri/frontend:1.0.0
    networks:
    - expense
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend